# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: covid-publish

on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: Publish to IPFS
      run: |
          chmod +x ./bin/run.sh
          ./bin/run.sh
      env:
        COVID_URL: ${{ secrets.COVID_URL }}
        COVID_KEY: ${{ secrets.COVID_KEY }}
        TEMPORAL_USER: ${{ secrets.TEMPORAL_USER }}
        TEMPORAL_PASS: ${{ secrets.TEMPORAL_PASS }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}          
